##make a numeric vector to use for the histogram
dataTime <- strptime(paste(data1$Date,data1$Time),format="%d/%m/%Y %H:%M:%S")
datasub1 <- as.numeric(data1$Sub_metering_1)
datasub2 <- as.numeric(data1$Sub_metering_2)
datasub3 <- as.numeric(data1$Sub_metering_3)
datagap <- as.numeric((levels(data1$Global_active_power))[data1$Global_active_power])
datagrp <- as.numeric((levels(data1$Global_reactive_power))[data1$Global_reactive_power])
datavol <- as.numeric((levels(data1$Voltage))[data1$Voltage])

##make the histogram (save to png)
png(filename = "Plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(dataTime, datagap, type = "l", ylab = "Global Active Power (kiloWatts)", xlab="")
plot(dataTime, datavol, type = "l", ylab = "Voltage", xlab="")
plot(dataTime, datasub1, type="l", ylab="Energy Submetering", xlab="")
lines(dataTime, datasub2, type="l", col="red")
lines(dataTime, datasub3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
plot(dataTime, datagrp, type = "l", ylab = "Global Reactive Power (kiloWatts)", xlab="")
dev.off() 
